name: Test

on:
  push:
    branches:
      - master

jobs:
  checkLicense:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.4.2
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - run: sh scripts/test.sh
        timeout-minutes: 5
